// <auto-generated />
using System;
using AnimeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeHub.Api.Migrations
{
    [DbContext(typeof(AnimeHubDbContext))]
    [Migration("20251103214301_ReworkGalleryImageCategoryToEnum")]
    partial class ReworkGalleryImageCategoryToEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeHub.Api.Entities.Anime", b =>
                {
                    b.Property<long>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnimeId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("AnimeId");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImage", b =>
                {
                    b.Property<long>("GalleryImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GalleryImageId"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("GalleryImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.HasKey("GalleryImageId");

                    b.HasIndex("GalleryImageCategoryId");

                    b.ToTable("GalleryImage");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImageCategory", b =>
                {
                    b.Property<int>("GalleryImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GalleryImageCategoryId");

                    b.ToTable("GalleryImageCategory");

                    b.HasData(
                        new
                        {
                            GalleryImageCategoryId = 1,
                            Name = "Standard Anime/Isekai"
                        },
                        new
                        {
                            GalleryImageCategoryId = 2,
                            Name = "Chibi Style"
                        });
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImage", b =>
                {
                    b.HasOne("AnimeHub.Api.Entities.GalleryImageCategory", "Category")
                        .WithMany("GalleryImages")
                        .HasForeignKey("GalleryImageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImageCategory", b =>
                {
                    b.Navigation("GalleryImages");
                });
#pragma warning restore 612, 618
        }
    }
}
