// <auto-generated />
using System;
using AnimeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeHub.Api.Migrations
{
    [DbContext(typeof(AnimeHubDbContext))]
    [Migration("20251105012744_AddAyamiProfileTables")]
    partial class AddAyamiProfileTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeHub.Api.Entities.Anime", b =>
                {
                    b.Property<long>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnimeId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("AnimeId");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiAccessory", b =>
                {
                    b.Property<int>("AyamiAccessoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AyamiAccessoryId"));

                    b.Property<int>("AttireId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("bit");

                    b.HasKey("AyamiAccessoryId");

                    b.HasIndex("AttireId");

                    b.ToTable("AyamiAccessories");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiAttire", b =>
                {
                    b.Property<int>("AyamiAttireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AyamiAttireId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hairstyle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("AyamiAttireId");

                    b.HasIndex("ProfileId");

                    b.ToTable("AyamiAttires");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiProfile", b =>
                {
                    b.Property<int>("AyamiProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AyamiProfileId"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Eyes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JapaneseFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JapaneseLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryEquipment")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vibe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AyamiProfileId");

                    b.ToTable("AyamiProfiles");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImage", b =>
                {
                    b.Property<long>("GalleryImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GalleryImageId"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("GalleryImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.HasKey("GalleryImageId");

                    b.HasIndex("GalleryImageCategoryId");

                    b.ToTable("GalleryImage");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImageCategory", b =>
                {
                    b.Property<int>("GalleryImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GalleryImageCategoryId");

                    b.ToTable("GalleryImageCategory");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiAccessory", b =>
                {
                    b.HasOne("AnimeHub.Api.Entities.Ayami.AyamiAttire", "Attire")
                        .WithMany("Accessories")
                        .HasForeignKey("AttireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attire");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiAttire", b =>
                {
                    b.HasOne("AnimeHub.Api.Entities.Ayami.AyamiProfile", "Profile")
                        .WithMany("Attires")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImage", b =>
                {
                    b.HasOne("AnimeHub.Api.Entities.GalleryImageCategory", "Category")
                        .WithMany("GalleryImages")
                        .HasForeignKey("GalleryImageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiAttire", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.Ayami.AyamiProfile", b =>
                {
                    b.Navigation("Attires");
                });

            modelBuilder.Entity("AnimeHub.Api.Entities.GalleryImageCategory", b =>
                {
                    b.Navigation("GalleryImages");
                });
#pragma warning restore 612, 618
        }
    }
}
